config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "flyers#index"

  resources :flyers
  resources :bands
  resources :venues

  namespace :api do
    resources :bands, only: [ :index ]
    resources :venues, only: [ :index ]
    get :search, to: "search#index"
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100 shadow-lg sticky top-0 z-50">
  <div class="navbar-start">
    <%= link_to root_path, class: "btn btn-ghost text-xl normal-case" do %>
      PDX Flyer Archive
    <% end %>
  </div>

  <div class="navbar-center hidden lg:flex">
    <div class="form-control relative"
          data-controller="global-search"
          data-global-search-url-value="/api/search"
          data-action="click@window->global-search#hide">
      <input
        type="text"
        placeholder="Search by band or venue..."
        class="input input-bordered w-96"
        autocomplete="off"
        data-global-search-target="input"
        data-action="input->global-search#search focus->global-search#showIfHasResults"
      />
      <div
        data-global-search-target="results"
        class="absolute top-full mt-2 w-full bg-base-100 shadow-xl rounded-box max-h-96 overflow-y-auto hidden z-50"
      ></div>
    </div>
  </div>

  <div class="navbar-end">
    <!-- Hamburger menu for mobile -->
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <li class="lg:hidden">
          <div class="form-control p-2 relative"
                data-controller="global-search"
                data-global-search-url-value="/api/search"
                data-action="click@window->global-search#hide">
            <input
              type="text"
              placeholder="Search..."
              class="input input-bordered input-sm w-full"
              autocomplete="off"
              data-global-search-target="input"
              data-action="input->global-search#search focus->global-search#showIfHasResults"
            />
            <div
              data-global-search-target="results"
              class="absolute top-full left-0 mt-2 w-full bg-base-100 shadow-xl rounded-box max-h-96 overflow-y-auto hidden z-50"
            ></div>
          </div>
        </li>
        <li><%= link_to "Flyers", flyers_path %></li>
        <li><%= link_to "Bands", bands_path %></li>
        <li><%= link_to "Venues", venues_path %></li>
        <li><a class="btn btn-primary btn-sm mt-2">Login / Sign Up</a></li>
      </ul>
    </div>

    <!-- Desktop menu -->
    <ul class="menu menu-horizontal px-1 hidden lg:flex">
      <li><%= link_to "Flyers", flyers_path %></li>
      <li><%= link_to "Bands", bands_path %></li>
      <li><%= link_to "Venues", venues_path %></li>
      <li><a class="btn btn-primary btn-sm ml-2">Login / Sign Up</a></li>
    </ul>
  </div>
</div>